<?php

namespace App;

use App\Notifications\LowQuantityStockNotification;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Notification;

class WarehouseStock extends Model
{
    protected $fillable = [
        'quantity',
        'material_id',
    ];

    public function material(){
        return $this->belongsTo(Material::class)->withTrashed();
    }

    public static function boot()
    {
        parent::boot (); // TODO: Change the autogenerated stub

        self::updated(function ($model){
            if ($model->quantity <= 10){
                $admin = User::where('is_admin',1)->where('id',7)->get();
                Notification::send($admin, new LowQuantityStockNotification($model));
            }
        });
    }
}
